### ISSUE TITLE
remove oauth key

### ISSUE THREAD

**Issue by zacdav** [tidyverse/website-analytics#3]
Noticed you uploaded the oauth-key.json, might be worth removing?

**Comment by jennybc** [comment]
This is not really a secret (or, rather treating it so is engaging in a bit of security theatre, which is sometimes required). It's not the same as an oauth token. You can't do anything with it, on its own. It's one of the 3 legs of 3-legged oauth. A user must still authenticate themselves with Google (legs 2 and 3) and authorize the app (leg 2) to help them get a token from Google (leg 3). Then you must also write your own API requests (leg 2, again). The best concentrated discussion of how to treat such credentials in open source work is here:

https://github.com/rclone/rclone/issues/309
